In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import sklearn

In [30]:
# import numpy as np
# import pandas as pd

# X_train = pd.read_csv('UCI HAR Dataset/UCI HAR Dataset/train/X_train.txt', sep="\s+", header=None).values

# y_train = pd.read_csv('UCI HAR Dataset/UCI HAR Dataset/train/y_train.txt', header=None).values.ravel()

# import pandas as pd
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

# X_test_path = r"UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt"
# X_test = pd.read_csv(X_test_path, delim_whitespace=True, header=None)

# y_test_path = r"UCI HAR Dataset\UCI HAR Dataset\test\y_test.txt"
# y_test = pd.read_csv(y_test_path, delim_whitespace=True, header=None)


<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ishika & divita\AppData\Local\Temp\ipykernel_13416\533281009.py:4: SyntaxWarning: invalid escape sequence '\s'
  X_train = pd.read_csv('UCI HAR Dataset/UCI HAR Dataset/train/X_train.txt', sep="\s+", header=None).values


In [31]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

X_train = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\train\X_train.txt", delim_whitespace=True, header=None)
y_train = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\train\y_train.txt", delim_whitespace=True, header=None)
X_test = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt", delim_whitespace=True, header=None)
y_test = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\test\y_test.txt", delim_whitespace=True, header=None)

y_train = y_train.values.ravel()
y_test = y_test.values.ravel()
 
X_train_flat = X_train.values
X_test_flat = X_test.values

clf = DecisionTreeClassifier(criterion="gini", random_state=46, min_samples_split=4, max_features='sqrt')

clf.fit(X_train_flat, y_train)

y_train_pred = clf.predict(X_train_flat)
y_test_pred = clf.predict(X_test_flat)

train_ac = accuracy_score(y_train, y_train_pred)
test_ac = accuracy_score(y_test, y_test_pred)

print(f"Accuracy on train dataset: {train_ac * 100:.2f}%")
print(f"Accuracy on test dataset: {test_ac * 100:.2f}%")

precision = precision_score(y_test, y_test_pred, average='weighted')
recall = recall_score(y_test, y_test_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_test_pred)

print(f"Precision on test dataset: {precision * 100:.2f}%")
print(f"Recall on test dataset: {recall * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy on train dataset: 99.54%
Accuracy on test dataset: 82.63%
Precision on test dataset: 82.92%
Recall on test dataset: 82.63%
Confusion Matrix:
[[446  22  28   0   0   0]
 [ 91 314  65   0   0   1]
 [ 43  48 327   0   0   2]
 [  0   0   0 392  96   3]
 [  0   0   0  83 449   0]
 [  0   0   0  14  16 507]]


In [25]:
conf_matrix = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[446  22  28   0   0   0]
 [ 91 314  65   0   0   1]
 [ 43  48 327   0   0   2]
 [  0   0   0 392  96   3]
 [  0   0   0  83 449   0]
 [  0   0   0  14  16 507]]
