In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import sklearn

In [1]:
import pandas as pd

# Read the text file into a DataFrame
# Adjust 'delim_whitespace=True' if the file is whitespace-delimited or use 'delimiter' for other delimiters
Xtrain = pd.read_csv(r'UCI HAR Dataset\UCI HAR Dataset\train\X_train.txt', delim_whitespace=True, header=None)

# Write the DataFrame to a CSV file
Xtrain.to_csv('Xtrain.csv', index=False, header=False)

Xtest = pd.read_csv(r'UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt', delim_whitespace=True, header=None)

# Write the DataFrame to a CSV file
Xtest.to_csv('Xtest.csv', index=False, header=False)



x------x------x-----x

In [3]:
import numpy as np

# Specify the path to your CSV file
csv_file_path1 = 'Xtrain.csv'
csv_file_path2 = 'Xtest.csv'

# Method 1: Using numpy.genfromtxt to handle missing values and complex data
# Load CSV file data into a NumPy array
data1 = np.genfromtxt(csv_file_path1, delimiter=',', skip_header=1)  # skip_header=1 to skip the header row, if present
data2 = np.genfromtxt(csv_file_path2, delimiter=',', skip_header=1) 
# Method 2: Using numpy.loadtxt if the CSV is well-formed with no missing values
# data = np.loadtxt(csv_file_path, delimiter=',', skiprows=1)  # skiprows=1 to skip the header row, if present

# Print the NumPy array to verify
print(data1.shape)
print(data2)


(7351, 561)
[[ 0.28602671 -0.01316336 -0.11908252 ... -0.69809082  0.28134292
  -0.08389801]
 [ 0.27548482 -0.02605042 -0.11815167 ... -0.70277146  0.28008303
  -0.0793462 ]
 [ 0.27029822 -0.03261387 -0.11752018 ... -0.69895383  0.28411379
  -0.077108  ]
 ...
 [ 0.34996609  0.03007744 -0.11578796 ... -0.65535684  0.27447878
   0.18118355]
 [ 0.23759383  0.01846687 -0.09649893 ... -0.65971859  0.26478161
   0.18756291]
 [ 0.15362719 -0.01843651 -0.13701846 ... -0.66008023  0.26393619
   0.1881034 ]]


x---------------------x----------------x

In [7]:
import numpy as np

# Load X_train data from text file
X_train = np.loadtxt(r"UCI HAR Dataset\UCI HAR Dataset\train\X_train.txt")

# Load y_train data from text file
# y_train = np.loadtxt(r"UCI HAR Dataset\train\y_train.txt")

# Load X_test data from text file
X_test = np.loadtxt(r"UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt")

# Load y_test data from text file
# y_test = np.loadtxt(r"UCI HAR Dataset\test\y_test.txt")

# Check the shapes of the loaded data
print(f"X_train shape: {X_train.shape}")
# print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
# print(f"y_test shape: {y_test.shape}")


X_train shape: (7352, 561)
X_test shape: (2947, 561)


In [30]:
# import numpy as np
# import pandas as pd

# X_train = pd.read_csv('UCI HAR Dataset/UCI HAR Dataset/train/X_train.txt', sep="\s+", header=None).values

# y_train = pd.read_csv('UCI HAR Dataset/UCI HAR Dataset/train/y_train.txt', header=None).values.ravel()

# import pandas as pd
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

# X_test_path = r"UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt"
# X_test = pd.read_csv(X_test_path, delim_whitespace=True, header=None)

# y_test_path = r"UCI HAR Dataset\UCI HAR Dataset\test\y_test.txt"
# y_test = pd.read_csv(y_test_path, delim_whitespace=True, header=None)


<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ishika & divita\AppData\Local\Temp\ipykernel_13416\533281009.py:4: SyntaxWarning: invalid escape sequence '\s'
  X_train = pd.read_csv('UCI HAR Dataset/UCI HAR Dataset/train/X_train.txt', sep="\s+", header=None).values


1. 

In [31]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

X_train = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\train\X_train.txt", delim_whitespace=True, header=None)
y_train = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\train\y_train.txt", delim_whitespace=True, header=None)
X_test = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt", delim_whitespace=True, header=None)
y_test = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\test\y_test.txt", delim_whitespace=True, header=None)

y_train = y_train.values.ravel()
y_test = y_test.values.ravel()
 
X_train_flat = X_train.values
X_test_flat = X_test.values

clf = DecisionTreeClassifier(criterion="gini", random_state=46, min_samples_split=4, max_features='sqrt')

clf.fit(X_train_flat, y_train)

y_train_pred = clf.predict(X_train_flat)
y_test_pred = clf.predict(X_test_flat)

train_ac = accuracy_score(y_train, y_train_pred)
test_ac = accuracy_score(y_test, y_test_pred)

print(f"Accuracy on train dataset: {train_ac * 100:.2f}%")
print(f"Accuracy on test dataset: {test_ac * 100:.2f}%")

precision = precision_score(y_test, y_test_pred, average='weighted')
recall = recall_score(y_test, y_test_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_test_pred)

print(f"Precision on test dataset: {precision * 100:.2f}%")
print(f"Recall on test dataset: {recall * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy on train dataset: 99.54%
Accuracy on test dataset: 82.63%
Precision on test dataset: 82.92%
Recall on test dataset: 82.63%
Confusion Matrix:
[[446  22  28   0   0   0]
 [ 91 314  65   0   0   1]
 [ 43  48 327   0   0   2]
 [  0   0   0 392  96   3]
 [  0   0   0  83 449   0]
 [  0   0   0  14  16 507]]


In [25]:
conf_matrix = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[446  22  28   0   0   0]
 [ 91 314  65   0   0   1]
 [ 43  48 327   0   0   2]
 [  0   0   0 392  96   3]
 [  0   0   0  83 449   0]
 [  0   0   0  14  16 507]]


2.

In [3]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
import tsfel

# Load raw accelerometer data
X_train_raw = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\train\X_train.txt", delim_whitespace=True, header=None)
y_train = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\train\y_train.txt", delim_whitespace=True, header=None)
X_test_raw = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\test\X_test.txt", delim_whitespace=True, header=None)
y_test = pd.read_csv(r"UCI HAR Dataset\UCI HAR Dataset\test\y_test.txt", delim_whitespace=True, header=None)

# Flatten y_train and y_test
y_train = y_train.values.ravel()
y_test = y_test.values.ravel()

# Debug: Check initial data shapes
print(f"Raw X_train shape: {X_train_raw.shape}")
print(f"Raw y_train shape: {y_train.shape}")
print(f"Raw X_test shape: {X_test_raw.shape}")
print(f"Raw y_test shape: {y_test.shape}")

# Extract features using TSFEL
# Get the TSFEL configuration file for standard features
cfg = tsfel.get_features_by_domain()

# Extract features for the train and test datasets
X_train_tsfel = tsfel.time_series_features_extractor(cfg, X_train_raw)
X_test_tsfel = tsfel.time_series_features_extractor(cfg, X_test_raw)

# Debug: Check feature data shapes after TSFEL extraction
print(f"Extracted X_train_tsfel shape: {X_train_tsfel.shape}")
print(f"Extracted X_test_tsfel shape: {X_test_tsfel.shape}")

# Check if the number of samples matches between features and labels
if X_train_tsfel.shape[0] != len(y_train):
    print("Mismatch in the number of samples between X_train and y_train!")

# Train a Decision Tree Classifier
clf = DecisionTreeClassifier(criterion="gini", random_state=46, min_samples_split=4, max_features='sqrt')

clf.fit(X_train_tsfel, y_train)

# Predict on train and test data
y_train_pred = clf.predict(X_train_tsfel)
y_test_pred = clf.predict(X_test_tsfel)

# Calculate accuracy, precision, recall, and confusion matrix
train_ac = accuracy_score(y_train, y_train_pred)
test_ac = accuracy_score(y_test, y_test_pred)
precision = precision_score(y_test, y_test_pred, average='weighted')
recall = recall_score(y_test, y_test_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_test_pred)

# Print the results
print(f"Accuracy on train dataset: {train_ac * 100:.2f}%")
print(f"Accuracy on test dataset: {test_ac * 100:.2f}%")
print(f"Precision on test dataset: {precision * 100:.2f}%")
print(f"Recall on test dataset: {recall * 100:.2f}%")
print("Confusion Matrix:")
print(conf_matrix)


Raw X_train shape: (7352, 561)
Raw y_train shape: (7352,)
Raw X_test shape: (2947, 561)
Raw y_test shape: (2947,)
*** Feature extraction started ***


C:\Users\ishika & divita\AppData\Local\Temp\ipykernel_17320\1718626556.py:28: UserWarning: Using default sampling frequency set in configuration file.
  X_train_tsfel = tsfel.time_series_features_extractor(cfg, X_train_raw)



*** Feature extraction finished ***
*** Feature extraction started ***


C:\Users\ishika & divita\AppData\Local\Temp\ipykernel_17320\1718626556.py:29: UserWarning: Using default sampling frequency set in configuration file.
  X_test_tsfel = tsfel.time_series_features_extractor(cfg, X_test_raw)



*** Feature extraction finished ***
Extracted X_train_tsfel shape: (1, 218229)
Extracted X_test_tsfel shape: (1, 218229)
Mismatch in the number of samples between X_train and y_train!


ValueError: Number of labels=7352 does not match number of samples=1